"""
Argo V2 — fresh LLM-generated project, delivered to Telegram.

Walks the full V2 funnel in one LLM call —

    Signal -> Observation -> Insight -> Bet (project)

— and produces a *fresh* project in Argo's frontier-scout voice (insight first,
then the bet/artifact/effort/upside), then sends it to Telegram.

This is the end-to-end "what should I build?" path: V2's observation generation
(argo_observe) carried through to a concrete project, instead of stopping at
observations. The insight is generated by the model, not retrieved from a pool.

Reuses, rather than duplicates:
  - argo_observe: input loading, provider routing, model call, .env/config
    (so providers stay non-hardcoded and ARGO_MODEL / keys work identically);
  - send_telegram.send_message: delivery (.env creds + certifi TLS).

Does NOT touch Argo V1 (argo.py), its BET_POOL, or energy tracking. If no API
key is available it writes the prompt only and does not send — never fabricates.

Run with:  python src/argo_project.py            (generate + send)
           python src/argo_project.py --no-send   (generate only, print)
"""

import json
import os
import sys
from datetime import datetime
from pathlib import Path

import argo_observe as observe
import send_telegram

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "argo" / "projects"
# Structured project log — one entry per generated project, so each can be rated
# later (see argo_rate.py). Lives in data/ alongside argo_bets.json.
PROJECTS_LOG = ROOT / "data" / "argo_projects.json"
TODAY = datetime.now().strftime("%Y-%m-%d")

# One canonical invite appended to every project Argo sends, so all paths (the
# weekly batch and the on-demand chat tool) offer the same three replies: rate
# it (keeps the 1-10 energy loop alive), lock it in, or ask for another. Plain
# text, no em dash (Argo voice).
def project_invite(project_id):
    return (f"\n\nThat's {project_id}. Reply 1-10 to rate how much you want to "
            "build it, SELECT to lock it in and get a kickoff plan, or ask for "
            "another.")


def log_project(project_text, model, source="argo"):
    """Append a project entry and return its id. Rating attaches to this later.

    `source` is "argo" for a generated project or "yiya" for one she brought, so
    recommend_project can weigh both kinds as candidates side by side."""
    log = []
    if PROJECTS_LOG.exists():
        log = json.loads(PROJECTS_LOG.read_text())

    project_id = f"P-{len(log) + 1:03d}"
    log.append({
        "id": project_id,
        "date": TODAY,
        "model": model,
        "source": source,
        "text": project_text,
        "energy": None,   # filled by argo_rate.py when you reply on Telegram
        "rated_at": None,
    })
    PROJECTS_LOG.write_text(json.dumps(log, indent=2) + "\n")
    return project_id


# ---------------------------------------------------------------------------
# The project prompt: generate the insight, THEN the bet that follows from it.
# This is generation, not retrieval — no pre-written projects anywhere.
# ---------------------------------------------------------------------------

PROJECT_INSTRUCTIONS = """You are Argo, a frontier scout. From the signals and
finding below, produce ONE fresh project worth building this week — but earn it
by NOTICING first.

Think in this order (internally):
1. Observation — something specific and concrete you actually notice in the
   signals below. A real detail, not a manufactured "everyone is doing X but few
   do Y" framing. Do NOT use the "everyone is captivated by / but few explore"
   move — it reads like a pitch deck. Just say the true, specific thing you see.
2. Insight — if that observation is true, what follows that nobody is saying yet?
   The insight is the point. The project is its consequence.
3. Bet — the smallest concrete project that tests or exploits the insight.

Then write a short Telegram message in this EXACT shape (no markdown headings,
short paragraphs, plain text). Lead with the insight, present the project as a
bet, close on the upside:

⚓ Argo

I've been watching something.

<2-4 short lines: the observation and the insight. One thought per line.>

This week's bet:
<a short, vivid project name>

<one or two sentences: what to build this week>

Artifact:
<the public thing it produces — repo / post / benchmark / demo>

Effort:
<one of: An evening / A weekend / A few days / A week>

Potential upside:
<why this is a bigger frontier than it looks>

Rules:
- The insight must be something the reader likely would NOT have thought of.
- Open with the concrete thing you noticed, not a sweeping "everyone is focused
  on X" generalization. Ground it in a specific signal.
- Do not output your internal observation/insight steps as separate sections —
  fold them into the message above.
- Output only the message, nothing else.
"""


# A weekly project needs real raw material to synthesize a non-obvious bet. The
# observation path uses 3 signals (a tight noticing); project generation starves
# on that and pads, so pull a wider slice of the (refreshed) frontier here.
PROJECT_SIGNALS = 10


def build_project_prompt():
    # Insight comes purely from the fresh signals. We deliberately do NOT pin a
    # prior finding (e.g. F-001) into the prompt: a single strong finding anchors
    # every insight to its theme, which is what made past projects all look the
    # same. Themes should follow the actual news.
    signals = observe.load_signals(limit=PROJECT_SIGNALS)
    signals_block = observe.format_signals(signals)

    # Fold in recent taste signals (lessons from screenshots Yiya sent) so the
    # project leans toward what she actually likes, not just what's in the feed.
    taste_block = ""
    try:
        import taste_signals
        taste = taste_signals.format_for_prompt()
        if taste:
            taste_block = f"\n---\n\n## {taste}\n"
    except Exception:
        pass  # taste is a nice-to-have; never block generation on it

    prompt = f"""{PROJECT_INSTRUCTIONS}
---

## Frontier signals

{signals_block}
{taste_block}"""
    return prompt, signals


def generate_project(prompt):
    """Return (project_text, model) or (None, errors) if generation failed.

    Reuses argo_observe's provider routing and model call, so OPENAI/ANTHROPIC
    keys, ARGO_MODEL, and the gpt-4.1 -> gpt-4o default all behave identically.
    """
    models = observe.resolve_models()
    runnable = [
        m for m in models
        if (p := observe.provider_for(m)) and os.environ.get(p["key_env"])
    ]
    if not runnable:
        return None, models  # caller reports which keys are needed

    errors = []
    for model in runnable:
        try:
            # generate_observations is a generic "send this prompt to the routed
            # model and return the text" call — reuse it for the project prompt.
            text = observe.generate_observations(prompt, model)
            return (text, model), None
        except Exception as exc:
            # Include type + underlying cause; the SDK's "Connection error"
            # otherwise hides the real reason (SSL / DNS / proxy / timeout).
            detail = f"{type(exc).__name__}: {exc}"
            cause = getattr(exc, "__cause__", None)
            if cause is not None:
                detail += f"  <- {type(cause).__name__}: {cause}"
            errors.append(f"{model}: {detail}")
    return None, errors


def _refresh_signals():
    """Refresh the signal store from the live feeds. Best-effort: never raises —
    on failure we fall back to whatever's already in the store."""
    try:
        import fetch_signals
        fetch_signals.main()
    except SystemExit:
        print("Signal refresh found nothing new; using the existing store.")
    except Exception as exc:
        print(f"Signal refresh failed ({type(exc).__name__}: {exc}); "
              "using the existing store.")


def make_project(refresh=True):
    """Generate ONE fresh project, log it, and return (project_id, text, model).

    The reusable core shared by the weekly batch (main) and the on-demand chat
    tool ("give me another"). Returns None if no model could generate. When
    refresh is True, pulls today's signals first."""
    if refresh:
        _refresh_signals()
    prompt, _ = build_project_prompt()
    result, _ = generate_project(prompt)
    if result is None:
        return None
    text, model = result
    text = text.strip()
    project_id = log_project(text, model)
    return project_id, text, model


SHAPE_INSTRUCTIONS = """You are Argo. Yiya brought you a project idea of her own.
Shape it into the SAME format you use for your own bets, so it sits comparably
next to them — but stay true to HER idea; sharpen it, don't replace it. Plain
text, no markdown, no em dashes.

⚓ Argo

I've been watching something.

<1-3 short lines: the real insight under her idea, grounded and specific>

This week's bet:
<a short, vivid name for HER project>

<one or two sentences: what to build this week>

Artifact:
<the public thing it produces>

Effort:
<one of: An evening / A weekend / A few days / A week>

Potential upside:
<why it matters, honest, not inflated>

Output only the message. Here is her idea:
"""


def shape_idea_into_project(idea):
    """Turn Yiya's rough idea into the standard project shape, log it as her
    candidate (source 'yiya'), and return (project_id, text, model). None if no
    model is available. Folds in her taste so the shaping respects it."""
    taste_block = ""
    try:
        import taste_signals
        taste = taste_signals.format_for_prompt()
        if taste:
            taste_block = f"\n\n(Keep these preferences in mind: {taste})"
    except Exception:
        pass
    prompt = f"{SHAPE_INSTRUCTIONS}{idea.strip()}{taste_block}"
    result, _ = generate_project(prompt)
    if result is None:
        return None
    text, model = result
    text = text.strip()
    project_id = log_project(text, model, source="yiya")
    return project_id, text, model


def main():
    no_send = "--no-send" in sys.argv

    # Refresh the signal store from the live frontier feeds first, so the project
    # is built from today's news, not a stale snapshot. Best-effort: if the fetch
    # fails (network/feeds down), fall back to whatever's already in the store
    # rather than blocking the weekly project.
    _refresh_signals()

    prompt, signals = build_project_prompt()

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    prompt_path = OUT_DIR / "project_job.md"
    prompt_path.write_text(prompt)

    print("\n🧭 Argo V2 — Fresh Project\n")
    print(f"Loaded {len(signals)} signals + F-001 as context:")
    for s in signals:
        print(f"  • {s['title']}")
    print(f"\nWrote reusable prompt: {prompt_path.relative_to(ROOT)}")

    result, failure = generate_project(prompt)

    if result is None:
        # failure is either the model list (no key) or a list of error strings.
        if all(isinstance(x, str) and ": " in x for x in failure):
            print("\nA key was available, but no model call succeeded:")
            for err in failure:
                print(f"  - {err}")
        else:
            needed = sorted({
                p["key_env"] for m in failure if (p := observe.provider_for(m))
            })
            print("\nNo API key available for the selected model(s): "
                  + ", ".join(failure))
            if needed:
                print("Set one of: " + ", ".join(needed)
                      + " (see docs/ARGO_LLM_SETUP.md).")
        print("\n⚠️  No project generated — nothing sent.\n")
        return

    project_text, model = result
    project_text = project_text.strip()

    latest_path = OUT_DIR / "latest.md"
    dated_path = OUT_DIR / f"{TODAY}.md"
    stamped = f"<!-- generated {TODAY} by {model} -->\n\n{project_text}\n"
    latest_path.write_text(stamped)
    dated_path.write_text(stamped)

    project_id = log_project(project_text, model)

    print(f"Generated project with: {model}")
    print(f"Wrote: {latest_path.relative_to(ROOT)}")
    print(f"Wrote: {dated_path.relative_to(ROOT)}")
    print(f"Logged: {PROJECTS_LOG.relative_to(ROOT)} ({project_id})")
    print("\n--- Project ---\n")
    print(project_text)
    print()

    if no_send:
        print("(--no-send: not sending to Telegram)\n")
        return

    # Invite a rating reply (argo_rate.py reads it back), plus select/another.
    send_telegram.send_message(project_text + project_invite(project_id))
    print()


if __name__ == "__main__":
    main()
